### PR TITLE
Update Travis build

### PR DESCRIPTION
**Pull request by ashawley**
- Remove sudo:false
- ~Rename skip_cleanup~
- Update Scala 2.12.10

### CODE REVIEW

**Comment by ashawley** [comment]
https://travis-ci.org/ThoughtWorksInc/sbt-api-mappings/builds/629788225

**Comment by Atry** [comment]
Why did you rename `skip_cleanup`?

**Comment by ashawley** [comment]
https://travis-ci.org/ThoughtWorksInc/sbt-api-mappings/builds/629881381/config

There were warnings in "View config" tab:

```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
deploy: deprecated key skip_cleanup (not supported in dpl v2, use cleanup)
```

Maybe I misunderstood?

**Comment by SethTisue** [comment]
since it was `skip_cleanup: true` before, maybe it should be `cleanup: false` now?

**Comment by ashawley** [comment]
Good point!  I will just punt the issue.  I don't understand how it should be fixed.

**Comment by Atry** [comment]
Looks good to me! Now merging...

**Pull request merged**
