### PR TITLE
Add jdk scripted test

### PR DESCRIPTION
**Pull request by ashawley**
I wanted to verify that adding Java's library to the `apiMappings` would work when running scaladoc, but found out that this may not be possible in Java 9 given the new module system?

Regardless, here's the WIP so far:

- I wrote a sbt-scripted test for the JCL.
- Warn when the boot class path is unavailable
- Handle Java 9 version in `java.specification.version`.

### CODE REVIEW

**Comment by Atry** [comment]
What is JCL?

**Comment by ashawley** [comment]
> What is JCL?

The Java Class Library.

**Comment by Atry** [comment]
Could you skip the regex tests on Java 9 since it always fails

**Comment by ashawley** [comment]
> Could you skip the regex tests on Java 9 since it always falls

Sure.  On Java 9, I've disabled the checks in the scripted test.

**Comment by ashawley** [comment]
The doc task still fails, because `-Xfatal-warnings` is set in the scripted test `scalacOptions`.

```
[error] A.scala:1:1: Could not find any member to link for "java.lang.Throwable".
[error] /**
[error] ^
[error] one error found
[error] (Compile / doc) Scaladoc generation failed
```

Disable it as well?

**Comment by Atry** [comment]
Yes, please

**Comment by ashawley** [comment]
Ok, nearly every aspect of the scripted test is disabled for Java 9 now.

**Comment by Atry** [comment]
I don't know if the log level of `boot class path not supported` should be an `info` or a `warn`. What's your thought?

**Comment by ashawley** [comment]
> I don't know if the log level of "boot class path not supported" should be an `info` or a `warn`.

Users will more likely see it if it's a warn, since it will be presented in the color yellow.  Scaladoc will `warn` when it doesn't find a reference, so its cause from sbt-api-mappings finding that "boot class path not supported", should match the log level of scaladoc.

**Comment by Atry** [comment]
Good catch!
I just changed the message to avoid the acronym JCL, in case of confusing ignorant people like me.

Now merging

**Comment by Atry** [comment]
Thank you!
@ashawley 👍

**Pull request merged**
