### PR TITLE
Scala 2.13.0-RC1 broken in JDK11

### PR DESCRIPTION
**Pull request by ashawley**
Not broken-broken, but links don't work.

### CODE REVIEW

**Comment by ashawley** [comment]
https://travis-ci.org/ThoughtWorksInc/sbt-api-mappings/builds/630196818

**Comment by ashawley** [comment]
Seems to be an issue upstream with Scaladoc.

https://github.com/scala/bug/issues/11839

**Comment by SethTisue** [comment]
that bug was fixed in 2.13.2 (though it caused a regression on Windows: https://github.com/scala/bug/issues/11955 ; fix will ship in 2.13.3)

**Comment by Atry** [comment]
Test updated to 2.13.8 
https://github.com/ThoughtWorksInc/sbt-api-mappings/blob/3.0.x/src/sbt-test/sbt-api-mappings/jdk/build.sbt#L9

**Pull request closed without merging**
