### PR TITLE
update sbt to 0.13.16 and establish 1.0.x compatibility

### PR DESCRIPTION
**Pull request by larsrh**

### CODE REVIEW

**Comment by larsrh** [comment]
Update to sbt 1.0.x is currently blocked by Play and Spark plugins. But this commit should bring everything well within the supported fragment of 1.0.x.

**Comment by Atry** [comment]
Play and Spark are not problems. We can simply remove them from tests.

Those functionalities can be proven by belief instead of test cases.

**Comment by Atry** [comment]
Would you mind rebasing it on `2.0.x-wip` branch please?

We don't have to make this plugin cross sbt versions. Let's build new version on sbt 1.0.x only.

**Comment by larsrh** [comment]
Tests green again 😄

**Comment by larsrh** [comment]
Ah, will do.

**Comment by larsrh** [comment]
I just checked the branch. There's no point rebasing my changes because you essentially duplicated my work.

**Pull request closed without merging**
